# Generated by Django 2.2.5 on 2019-09-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190927_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='hunter',
        ),
    ]
