# Generated by Django 2.2.5 on 2019-09-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190928_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hunter',
        ),
    ]
